#!/bin/sh

export LD_PRELOAD="/usr/lib/interposers/libinterpose_syscall.so"

# Default is to block SYS_renameat2. Uncomment below to allow it through.
# export ALLOW_RENAMEAT2="true"

if [ "$1" = "--strace" ]
then
	shift
	unset INTERPOSE_SYSCALL_LOGFILE
	exec strace -e write -s 120 "$@"
else
	if [ -z "${INTERPOSE_SYSCALL_LOGFILE}" ]
	then
		export INTERPOSE_SYSCALL_LOGFILE="/tmp/syscall.log"
	fi
	exec "$@"
fi
